permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: pages
  cancel-in-progress: true
name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    environment: env.qa
    env:
       BASE_URL: ${{ vars.BASE_URL }}
       ORANGE_USERNAME: ${{ secrets.ORANGE_USERNAME }}
       ORANGE_PASSWORD: ${{ secrets.ORANGE_PASSWORD }}    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Display Node Version
      run: node -v
    - name: Display NPM Version
      run: npm -v
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - name: Install Allure
      if: always()
      run: npm install -g allure-commandline
    - name: Check Allure Results
      if: always()
      run: ls -R allure-results
    - name: Generate Allure Report
      if: always()
      run: allure generate allure-results --clean -o allure-report
    - name: Upload GitHub Pages Artifact
      if: always()
      uses: actions/upload-pages-artifact@v3
      with:
        path: allure-report
    - name: Deploy to GitHub Pages
      if: always()
      uses: actions/deploy-pages@v4
    - name: Upload Allure Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report/
        retention-days: 30
    - name: Upload Playwright Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: |
          playwright-report/
          test-results/
        retention-days: 30